[build]
  command = "python3 -m venv .venv && .venv/bin/pip install -r requirements.txt && make static"
  publish = "build/"
  environment = { PYTHON_VERSION = "3.12" }

[[redirects]]
  from = "/"
  to = "/2026/"
  status = 301
  force = true

[[redirects]]
  from = "/2025/fr/programme/"
  to = "/2026/fr/programme/"
  status = 301
  force = true